=== CAMP09/Lenguajes-XML-DTD-XSD/Actividad_2_Carmen/Biblioteca.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <annotation>
        <documentation>
            Esquema de una biblioteca, con tres elementos principales:libros, revistas y periodicos.
        </documentation>
    </annotation>
<element name="biblioteca">
    <complexType>
        <sequence>
 <!--El elemento libro tendrá que figurar como mínimo de 1 vez y hasta un número ilimitado de veces-->       
            <element name="libros">
                <complexType>
                    <sequence> 
                     <element name="libro" minOccurs="1" maxOccurs="unbounded">
                        <complexType>
                            <sequence>
 <!--El elemento "titulo_libro" será de tipo string tendrá entre 5 y 50 caracteres-->                            
                                <element name="titulo_libro">
                                <simpleType>
                                    <restriction base="string">
                                        <minLength value="5"/>
                                        <maxLength value="50"/>
                                    </restriction>
                                </simpleType>
                                </element>
                                <element name="capitulos">
                                    <complexType>
                                        <sequence>
 <!--Cada libro podrá tener entre 1 y 10 capítulos y los elemntos que lo componen tendrán que figurar en el mismo orden que se detalla -->
                                            <element name="capitulo" minOccurs="1" maxOccurs="10">
                                                <complexType>
                                                    <sequence>
                                                        <element name="titulo_capitulo" type="string"></element>
                                                        <element name="contenido" ></element>
                                                    </sequence>
 <!--Los atributos n_pag_cap y enlace son de tipo integer y string respectivamente -->
                                                        <attribute name="n_pag_cap" type="integer"></attribute>
                                                        <attribute name="enlace" type="string"></attribute>                 
                                                </complexType>
                                            </element>    
                                        </sequence>                                    
                                    </complexType>
                                </element>    
                                <element name="indice" type="string"/>
 <!--La sinopsis será un elmento vacío -->
                                <element name="sinopsis">
                                    <complexType/>
                                </element>
                            </sequence>
<!--En relación a los atributos, el "id" es obligatorio además máximo tendrá 5 caracteres de los cuales uno es la letra a la que hace referencia "L" sequido de 4 dígitos entre 0 y 5  -->
                                <attribute name="id" use="required">
                                    <simpleType>
                                        <restriction base="string">
                                            <maxLength value="5"></maxLength>
                                            <pattern value="[L][0-5]{4}"></pattern>
                                        </restriction>
                                    </simpleType>                             
                                </attribute>
<!-- El atributo "tipo_clase" también será obligatorio y sólo podrá tener uno de los 3 valores que se detallan ( novela, infantil o didactico) -->
                                <attribute name="tipo_clase" use="required">
                                    <simpleType>
                                        <restriction base="string">
                                            <enumeration value="novela"></enumeration>
                                            <enumeration value="infantil"></enumeration>
                                            <enumeration value="didactico"></enumeration>
                                        </restriction>
                                    </simpleType>
                                </attribute>
<!--El número de páginas no podrá ser mayor de 2 cifras  -->
                                <attribute name="n_pag_libro">
                                    <simpleType>
                                        <restriction base="integer">
                                            <totalDigits value="2"></totalDigits>
                                        </restriction>
                                    </simpleType>
                                </attribute>
                        </complexType>
                     </element>
                    </sequence>
                </complexType>                                           
            </element>

<!--El elemento revista tendrá que figurar como mínimo de 1 a 100 veces además incluirá todos los elemntos que hay dentro de "revista" siendo el orden indistinto--> 
            <element name="revistas">
                <complexType>
                    <sequence>
                        <element name="revista" minOccurs="1" maxOccurs="100">
                            <complexType>
                                <all>
                                    <element name="titulo" type="string"></element>
 <!--El elemento "numero_revista" podrá oscilar entre 1 y 999  -->
                                    <element name="numero_revista">
                                        <simpleType>
                                            <restriction base="integer">
                                                <minInclusive value="1"></minInclusive>
                                                <maxExclusive value="999"></maxExclusive>
                                            </restriction>
                                        </simpleType>                                    
                                    </element>
                                    <element name="indice_contenido" type="string"></element>
                                    <element name="secciones">
                                        <complexType>
                                            <sequence>
                                                <element name ="seccion">
                                                    <complexType>
                                                        <sequence>                                                   
                                                            <element name="contenido"></element>
                                                                                                                     
                                                        </sequence>
                                                    <attribute name="enlace" type="string"></attribute>
                                                    <attribute name="n_pag_seccion" type="integer" ></attribute> 
                                                    </complexType>
                                                </element>
                                                </sequence>                                                
                                            </complexType>                                            
                                    </element>                                 
                                </all>
<!--En relación a los atributos, el "id" es obligatorio además máximo tendrá 5 caracteres de los cuales uno es la letra a la que hace referencia "R" sequido de 4 dígitos entre 0 y 5  -->
                                    <attribute name="id" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <maxLength value="5"></maxLength>
                                                <pattern value="[R][0-5]{4}"></pattern>
                                            </restriction>
                                        </simpleType>                             
                                    </attribute>
<!-- El atributo "tipo_clase" también será obligatorio y sólo podrá tener uno de los 5 valores que se detallan ( informatica, corazon, coches, investigacio y otras) -->                                  
                                    <attribute name="tipo_clase" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <enumeration value="informatica"></enumeration>
                                                <enumeration value="corazon"></enumeration>
                                                <enumeration value="coches"></enumeration>
                                                <enumeration value="investigacion"></enumeration>
                                                <enumeration value="otras"></enumeration>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
<!--El número de páginas de las revistas no podrá ser superior a 2 cifras -->
                                    <attribute name="n_pag_revista">
                                        <simpleType>
                                            <restriction base="integer">
                                                <totalDigits value="2"></totalDigits>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                            </complexType>                             
                        </element>
                    </sequence>                       

                </complexType>
            </element>

<!--El elemento periodico tendrá que figurar como mínimo de 1 a 10 veces, los elementos que lo componen van en secuencia--> 
            <element name="periodicos">
                <complexType>
                    <sequence>                    
                     <element name="periodico" minOccurs="1" maxOccurs="10">
                      <complexType>
                        <sequence>
                            <element name ="secciones_periodico">
                                <complexType>
                                    <sequence>
<!-- Como mínimo habrá 1 sección de periódico y como máximo 5 -->
                                    <element name ="seccion_p" minOccurs="1" maxOccurs="5">
                                        <complexType>
                                            <sequence>                                                        
                                                <element name="articulo"> </element>
                                                                                                       
                                            </sequence>
                                                <attribute name="autor" type="string"></attribute>
<!--El tipo de sección será un campo obligatorio y tendrá como restricción la clasificación en alguno de estos 5 valores (economia, opinion, deprotes, nacional e internacional  -->
                                                <attribute name="tipo_seccion" use="required" >
                                                    <simpleType>
                                                        <restriction base="string">
                                                            <enumeration value="economia"></enumeration>
                                                            <enumeration value="opinion"></enumeration>
                                                            <enumeration value="deportes"></enumeration>
                                                            <enumeration value="nacional"></enumeration>
                                                            <enumeration value="internacional"></enumeration>
                                                        </restriction>
                                                    </simpleType>
                                                </attribute> 
                                        </complexType>
                                    </element>
                                    </sequence>                                                
                                </complexType>                                         
                            </element>
                            <element name ="indice_p" >
                                <complexType/>
                            </element>
                            <element name ="contenido_p"></element>               
                        </sequence>
                            <attribute name="enlace" type="string"></attribute>
<!--En relación a los atributos, el "id" es obligatorio además máximo tendrá 5 caracteres de los cuales uno es la letra a la que hace referencia "P" sequido de 4 dígitos entre 0 y 9  -->
                            <attribute name="id" use="required">
                                <simpleType>
                                    <restriction base="string">
                                        <maxLength value="5"></maxLength>
                                        <pattern value="[P][0-9]{4}"></pattern>
                                    </restriction>
                                </simpleType>                             
                            </attribute>
 <!--El atributo "tipo_clase" de periódico será obligatorio y sólo podrá ser uno de los dos siguientes:nacional o internacional  -->
                            <attribute name="tipo_clase" use="required">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="nacional"></enumeration>
                                        <enumeration value="internacional"></enumeration>                                        
                                    </restriction>
                                </simpleType>
                            </attribute>
                            <attribute name="fecha_publicacion" type="date"></attribute>
                        </complexType> 
                      </element>    
                    </sequence>
                </complexType>
            </element>
        </sequence>      
    </complexType>
</element>
</schema>

=== CAMP09/Lenguajes-XML-DTD-XSD/Actividad_2_Carmen/Biblioteca.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- El siguiente archivo XML está validado  con DTD y con XSD el elemnto raíz es "biblioteca"
y de la misma hay tres elementos principales : libros, revistas y periodicos-->

<!-- DTD -->
 <!-- <!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">     -->

<!-- XSD -->
  <biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        	xsi:noNamespaceSchemaLocation= "biblioteca.xsd"> 

  <!-- <biblioteca>    -->
	<libros>
		<libro id="L1000" tipo_clase="novela" n_pag_libro="70">
			<titulo_libro>El expreso de Tokio</titulo_libro>
			<capitulos>
				<capitulo n_pag_cap="13">
					<titulo_capitulo>Los Testigos</titulo_capitulo>
					<contenido enlace="biblioteca/libros/novelas/elexpresodetokio/lostestigos"></contenido>
				</capitulo>
				<capitulo n_pag_cap="24">
					<titulo_capitulo>Un doble suicidio</titulo_capitulo>
					<contenido enlace="biblioteca/libros/novelas/elexpresodetokio/undoblesuicidio"></contenido>
				</capitulo>
				<capitulo n_pag_cap="16">
					<titulo_capitulo>Las dos estaciones de Kashii</titulo_capitulo>
					<contenido
						enlace="biblioteca/libros/novelas/elexpresodetokio/lasdosestacionesdekashii"></contenido>
				</capitulo>
				<capitulo n_pag_cap="17">
					<titulo_capitulo>Los pasajeros de Tokio</titulo_capitulo>
					<contenido
						enlace="biblioteca/libros/novelas/elexpresodetokio/lospasajerosdetokio"></contenido>
				</capitulo>

			</capitulos>

			<indice>Indice</indice>

			<sinopsis></sinopsis>
		</libro>

		<libro id="L2000" tipo_clase="infantil" n_pag_libro="15">
			<titulo_libro>Las aventuras de Pinocho</titulo_libro>
			<capitulos>

				<capitulo n_pag_cap="3">
					<titulo_capitulo>Capitulo I</titulo_capitulo>
					<contenido enlace="biblioteca/libros/infantil/lasaventurasdepinocho/capituloI"></contenido>
				</capitulo>
				<capitulo n_pag_cap="4">
					<titulo_capitulo>Capitulo II</titulo_capitulo>
					<contenido enlace="biblioteca/libros/infantil/lasaventurasdepinocho/capituloII"></contenido>
				</capitulo>
				<capitulo n_pag_cap="5">
					<titulo_capitulo>Capitulo III</titulo_capitulo>
					<contenido enlace="biblioteca/libros/infantil/lasaventurasdepinocho/capituloIII"></contenido>
				</capitulo>
				<capitulo n_pag_cap="6">
					<titulo_capitulo>Capitulo IV</titulo_capitulo>
					<contenido enlace="biblioteca/libros/infantil/lasaventurasdepinocho/capituloIV"></contenido>
				</capitulo>

			</capitulos>

			<indice>Indice</indice>

			<sinopsis></sinopsis>

		</libro>

		<libro id="L3000" tipo_clase="didactico" n_pag_libro="7">
			<titulo_libro>Breve ortografia escolar</titulo_libro>
			<capitulos>
				<capitulo n_pag_cap="2">
					<titulo_capitulo>Reglas generales</titulo_capitulo>
					<contenido enlace="biblioteca/libros/didactico/breveortografiaescolar/reglasgenerales"></contenido>
				</capitulo>
				<capitulo n_pag_cap="1">
					<titulo_capitulo>Reglas del acento</titulo_capitulo>
					<contenido enlace="biblioteca/libros/didactico/breveortografiaescolar/reglasdelacento"></contenido>
				</capitulo>
				<capitulo n_pag_cap="2">
					<titulo_capitulo>Reglas de la -b</titulo_capitulo>
					<contenido enlace="biblioteca/libros/didactico/breveortografiaescolar/reglasdela-b"></contenido>
				</capitulo>
				<capitulo n_pag_cap="2">
					<titulo_capitulo>Reglas de la -v</titulo_capitulo>
					<contenido enlace="biblioteca/libros/didactico/breveortografiaescolar/reglasdela-v"></contenido>
				</capitulo>

			</capitulos>

			<indice>Indice</indice>

			<sinopsis></sinopsis>

		</libro>
	</libros>


	<revistas>
		<revista id="R1000" tipo_clase="informatica" n_pag_revista="67">
			<titulo>Computer Hoy</titulo>
			<numero_revista>627</numero_revista>
			<indice_contenido>Contenido</indice_contenido>
			<secciones>
				<seccion n_pag_seccion="1">
					<contenido enlace="http//:revistainformatica.com"> </contenido>
				</seccion>
			</secciones>
		</revista>

		<revista id="R2000" tipo_clase="corazon" n_pag_revista="50">
			<titulo>Hola</titulo>
			<numero_revista>525</numero_revista>
			<indice_contenido>Contenido</indice_contenido>
			<secciones>
				<seccion n_pag_seccion="3">
					<contenido enlace="http//:revistacorazon.com"> </contenido>
				</seccion>
			</secciones>
		</revista>

		<revista id="R3000" tipo_clase="coches" n_pag_revista="50">
			<titulo>Turini</titulo>
			<numero_revista>26</numero_revista>
			<indice_contenido>Contenido</indice_contenido>
			<secciones>
				<seccion n_pag_seccion="4">
					<contenido enlace="http//:revistacoches.com"> </contenido>
				</seccion>
			</secciones>
		</revista>

		<revista id="R4000" tipo_clase="investigacion" n_pag_revista="80">
			<titulo>Nature</titulo>
			<numero_revista>733</numero_revista>
			<indice_contenido>Contenido</indice_contenido>
			<secciones>
				<seccion n_pag_seccion="6">
					<contenido enlace="http//:revistainvestigacion.com"> </contenido>
				</seccion>
			</secciones>
		</revista>

		<revista id="R5000" tipo_clase="otras" n_pag_revista="54">
			<titulo>Hogar</titulo>
			<numero_revista>125</numero_revista>
			<indice_contenido>Contenido</indice_contenido>
			<secciones>
				<seccion n_pag_seccion="4">
					<contenido enlace="http//:revistaotros.com"> </contenido>
				</seccion>
			</secciones>
		</revista>
	</revistas>


	<periodicos>
		<periodico id="P6000" tipo_clase="nacional" fecha_publicacion="2023-05-02">
			<secciones_periodico>
				<seccion_p tipo_seccion="economia">
					<articulo autor="Emilio Ontiveros"> </articulo>
				</seccion_p>
				<seccion_p tipo_seccion="opinion">
					<articulo autor="Juan Soto"> </articulo>
				</seccion_p>
				<seccion_p tipo_seccion="deportes">
					<articulo autor="Antonio Lobato"></articulo>
				</seccion_p>
				<seccion_p tipo_seccion="nacional">
					<articulo autor="José María Carrascal"></articulo>
				</seccion_p>
				<seccion_p tipo_seccion="internacional">
					<articulo autor=" Jordi Pérez "></articulo>
				</seccion_p>
			</secciones_periodico>

			<indice_p></indice_p>
			<contenido_p enlaces="http//:elperiodico.com"></contenido_p>

		</periodico>

		<periodico id="P7000" tipo_clase="internacional" fecha_publicacion="2022-10-01">
			<secciones_periodico>
				<seccion_p tipo_seccion="economia">
					<articulo autor="Warrent Buffet"></articulo>
				</seccion_p>

				<seccion_p tipo_seccion="opinion">
					<articulo autor="Thomas Friedman"></articulo>
				</seccion_p>

				<seccion_p tipo_seccion="deportes">
					<articulo autor="Tania Ganguli"></articulo>
				</seccion_p>

				<seccion_p tipo_seccion="nacional">
					<articulo autor="Linda Qiu"></articulo>
				</seccion_p>

				<seccion_p tipo_seccion="internacional">
					<articulo autor="Andrew Testa"></articulo>
				</seccion_p>
			</secciones_periodico>

			<indice_p></indice_p>
			<contenido_p enlaces="http//:elperiodico.com"></contenido_p>
		</periodico>

	</periodicos>

</biblioteca>
