=== CAMP09/Lenguajes-XML-DTD-XSD/Actividad2_XML/biblioteca.dtd
<!-- Los elementos libro, periodico y revista podrÃ¡n aparecer en la biblioteca entre 0 y n veces -->

<!ELEMENT biblioteca (libro*,periodico*,revista*)>

<!-- Elemento libro-->

<!ELEMENT libro (titulo,capitulos,indice,sinopsis)>
<!ATTLIST libro id CDATA #REQUIRED>
<!ATTLIST libro tipo_clase (novela | infantil | didactico) #REQUIRED>
<!ATTLIST libro num_pag CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulos (capitulo+)>
<!ELEMENT capitulo (titulo_capitulo, contenido)>
<!ATTLIST capitulo num_pag CDATA #REQUIRED>
<!ELEMENT titulo_capitulo (#PCDATA)>
<!ELEMENT contenido EMPTY>
<!ATTLIST contenido enlace CDATA #REQUIRED>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>

<!-- Elemento periodico-->

<!ELEMENT periodico (secciones,indice)>
<!ATTLIST periodico id CDATA #REQUIRED>
<!ATTLIST periodico tipo_clase (nacional | internacional) #REQUIRED>
<!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>
<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion (articulos)>
<!ATTLIST seccion tipo (economica | opinion | deportes | nacional | internacional) #IMPLIED>
<!ATTLIST seccion num_pag CDATA #IMPLIED>
<!ELEMENT articulos (articulo*, contenido*)>
<!ATTLIST articulo autor CDATA #REQUIRED>
<!ELEMENT articulo (contenido)>

<!-- Elemento revista-->

<!ELEMENT revista (titulo,numero_revista,indice,secciones_revista)>
<!ATTLIST revista id CDATA #REQUIRED>
<!ATTLIST revista tipo_clase (informatica | corazon | coches | investigacion | otras) #REQUIRED>
<!ELEMENT secciones_revista (seccion_revista+)>
<!ELEMENT seccion_revista (contenido)>
<!ATTLIST seccion_revista num_pag CDATA #REQUIRED>
<!ATTLIST revista num_pag CDATA #REQUIRED>
<!ELEMENT numero_revista (#PCDATA)>

=== CAMP09/Lenguajes-XML-DTD-XSD/Actividad2_XML/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd"> 

<!-- <biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="biblioteca.xsd"> -->
<biblioteca>

    <libro id="L0000" tipo_clase="novela" num_pag="150">
        <titulo> Titulo del libro </titulo>
        <capitulos>
            <capitulo num_pag="150">
                <titulo_capitulo>Titulo capitulo</titulo_capitulo>
                <contenido enlace="www.libros.com/capitulo1"></contenido>
            </capitulo>
            <capitulo num_pag="136">
                <titulo_capitulo>Titulo capitulo</titulo_capitulo>  
                <contenido enlace="www.libros.com/capitulo2"></contenido>
            </capitulo>
        </capitulos>
        <indice> Indice </indice>
        <sinopsis> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tincidunt ultricies euismod. Quisque quis nisl massa. Aliquam suscipit, nulla at. </sinopsis>
    </libro>

    <periodico id="P0000" tipo_clase="nacional" fecha_publicacion="2023-05-09">
        <secciones>
            <seccion tipo="economica">
                <articulos>
                    <articulo autor="Alejandro Aguiar">
                        <contenido enlace="www.periodoco.com/economia1"></contenido>
                    </articulo>
                    <articulo autor="Alejandro Aguiar">
                        <contenido enlace="www.periodoco.com/economia2"></contenido>
                    </articulo>
                </articulos>
            </seccion>
            <seccion tipo="deportes">
                <articulos>
                    <articulo autor="Alejandro Aguiar">
                        <contenido enlace="www.periodoco.com/deportes1"></contenido>
                    </articulo>
                    <articulo autor="Alejandro Aguiar">
                        <contenido enlace="www.periodoco.com/deportes2"></contenido>
                    </articulo>
                </articulos>
            </seccion>
        </secciones>
        <indice> Indice </indice>
    </periodico>

    <revista id="R0000" tipo_clase="coches" num_pag="80">
        <titulo> Titulo de la Revista</titulo>
        <numero_revista> 5023 </numero_revista>
        <indice> Indice </indice>
        <secciones_revista>
            <seccion_revista num_pag="10">
                <contenido enlace="www.revista.com/seccion1"></contenido>
            </seccion_revista>
            <seccion_revista num_pag="8">
                <contenido enlace="www.revista.com/seccion2"></contenido>
            </seccion_revista>
        </secciones_revista>
    </revista>

</biblioteca>
