=== CAMP09/Lenguajes-XML-DTD-XSD/Actividad2 _Andres/biblioteca.dtd
<!ELEMENT biblioteca (libro, revista, periodico)>

<!ATTLIST libro id ID #REQUIRED>
<!ELEMENT libro (titulo, capitulos, indice, sinopsis)>
<!ATTLIST libro tipo_clase (novela | infantil | did치ctico) #REQUIRED>
<!ATTLIST libro pags CDATA #REQUIRED>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulos (capitulo)>

<!ELEMENT capitulo (titulo, contenido)>
<!ATTLIST capitulo pags CDATA #REQUIRED>

<!ELEMENT contenido (#PCDATA)>
<!ATTLIST contenido info CDATA #IMPLIED>

<!ELEMENT indice (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>

<!ELEMENT revista (titulo, numero, indice, secciones)>
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo_clase (inform치tica | coraz칩n | coches | investigaci칩n | otras) #REQUIRED>
<!ATTLIST revista pags CDATA #REQUIRED>

<!ELEMENT numero (#PCDATA)>

<!ELEMENT secciones (contenido)>
<!ATTLIST secciones pags CDATA #IMPLIED>

<!ELEMENT periodico (indice, seccion)>
<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST periodico tipo_clase (nacional | internacional) #REQUIRED>
<!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>

<!ELEMENT seccion (articulo)>
<!ATTLIST seccion tipo_seccion (economica | opinion | deportes | nacional | internacional) #REQUIRED>

<!ELEMENT articulo (contenido)>
<!ATTLIST articulo autor CDATA #IMPLIED>

=== CAMP09/Lenguajes-XML-DTD-XSD/Actividad2 _Andres/biblioteca_para_DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">

<biblioteca>
        <libro id="L0000" tipo_clase="novela" pags="">
            <titulo></titulo>
            <capitulos>
                <capitulo pags="">
                    <titulo></titulo>
                    <contenido info="enlace"></contenido>
                </capitulo>
            </capitulos>
            <indice></indice>
            <sinopsis></sinopsis>
        </libro>

    <revista id="R0000" tipo_clase="informÃ¡tica" pags="">
        <titulo></titulo>
        <numero></numero>
        <indice></indice>
        <secciones pags="">
            <contenido info="enlace"></contenido>
        </secciones>
    </revista>

    <periodico id="P0000" tipo_clase="nacional" fecha_publicacion="fecha">
        <indice></indice>
        <seccion tipo_seccion="economica">
            <articulo autor="nombre">
                <contenido info="enlace"></contenido>
            </articulo>
        </seccion>
    </periodico>
</biblioteca>
