=== CAMP09/Lenguajes-XML-DTD-XSD/Actividad2 _Andres/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- DOCUMENTACION-->

    <xs:annotation>
        <xs:documentation>
            Este es el esquema de validación del XML de una biblioteca en red.
        </xs:documentation>
    </xs:annotation>

    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>

            <!-- ELEMENTO LIBRO-->
            <xs:element name="libro" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>

                    <!-- Elementos de Libro-->
                    <xs:sequence>

                        <!-- TITULO-->
                        <xs:element name="titulo" type="xs:string"/>

                        <!-- CAPITULO -->
                        <xs:element name="capitulo" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="titulo" type="xs:string"></xs:element>
                                    <xs:element name="contenido">
                                        <xs:complexType>
                                            <!-- Atributo INFO de CONTENIDO-->
                                            <xs:attribute name="info" type="xs:string" use="optional"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>

                                <!-- Atributo PAGS de CAPITULO-->
                                <xs:attribute name="pags" type="xs:integer"/>
                            </xs:complexType>  
                        </xs:element>
                           
                        <!-- INDICE-->  
                        <xs:element name="indice" type="xs:string"></xs:element>

                        <!-- SINOPSIS-->  
                        <xs:element name="sinopsis" type="xs:string"></xs:element>
                    </xs:sequence>

                    <!-- Atributos LIBRO: ID-->
                    <xs:attribute name="id" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="L[0-9]{4}"></xs:pattern>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>

                    <!-- Atributos LIBRO: TIPO_CLASE-->
                    <xs:attribute name="tipo_clase" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="novela"/>
                                <xs:enumeration value="infantil"/>
                                <xs:enumeration value="didáctico"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>


                    <!-- Atributos LIBRO: PAGS-->
                    <xs:attribute name="pags" type="xs:integer"></xs:attribute>

                </xs:complexType>
            </xs:element>



            <!-- ELEMENTO REVISTA-->
            <xs:element name="revista" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>

                    <!-- Elementos de REVISTA-->
                    <xs:sequence>
                        <!-- TITULO-->
                        <xs:element name="titulo" type="xs:string"/>
                        <!-- NUMERO-->
                        <xs:element name="numero" type="xs:integer"></xs:element>
                        <!-- INDICE-->
                        <xs:element name="indice" type="xs:string"></xs:element>
                        <!-- SECCION_R-->
                        <xs:element name="seccion_r" minOccurs="1" maxOccurs="7">
                            <xs:complexType>
                                <xs:sequence>
                                    <!-- CONTENIDO-->
                                    <xs:element name="contenido">
                                        <xs:complexType>
                                            <!-- Atributo INFO de CONTENIDO-->
                                            <xs:attribute name="info" type="xs:string" use="optional"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>

                                <!-- Atributos SECCION: PAGS-->
                                <xs:attribute name="pags" type="xs:integer"></xs:attribute>
                                
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    
                    <!-- Atributos REVISTA: ID-->
                    <xs:attribute name="id" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="R[0-9]{4}"></xs:pattern>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>

                    <!-- Atributos REVISTA: TIPO_CLASE-->
                    <xs:attribute name="tipo_clase" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="informática"/>
                                <xs:enumeration value="corazón"/>
                                <xs:enumeration value="coches"/>
                                <xs:enumeration value="investigación"/>
                                <xs:enumeration value="otras"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>


                    <!-- Atributos REVISTA: PAGS-->
                    <xs:attribute name="pags" type="xs:integer" use="optional"></xs:attribute>

                </xs:complexType>
            </xs:element>



            <!-- ELEMENTO PERIODICO-->
            <xs:element name="periodico" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>

                    <!-- Elementos de PERIODICO-->
                    <xs:sequence>

                        <!-- INDICE-->
                        <xs:element name="indice" type="xs:string"/>

                        <!-- SECCION_P-->
                        <xs:element name="seccion_p" minOccurs="1" maxOccurs="7">
                            <xs:complexType>
                                <xs:sequence>

                                    <!-- ARTICULO-->
                                    <xs:element name="articulo" minOccurs="1" maxOccurs="5">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="contenido">
                                                    <xs:complexType>
                                                        <!-- Atributo INFO de CONTENIDO-->
                                                        <xs:attribute name="info" type="xs:string" use="optional"/>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                            <!-- Atributo AUTOR de ARTICULO-->
                                            <xs:attribute name="autor" type="xs:string" use="optional"/>       

                                        </xs:complexType>  
                                    </xs:element>
                                </xs:sequence>

                                <!-- Atributos SECCION: TIPO_SECCION-->
                                <xs:attribute name="tipo_seccion" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="economica"/>
                                            <xs:enumeration value="opinion"/>
                                            <xs:enumeration value="deportes"/>
                                            <xs:enumeration value="nacional"/>
                                            <xs:enumeration value="internacional"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>

                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>

                    <!-- Atributos PERIODICO: ID-->
                    <xs:attribute name="id" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="P[0-9]{4}"></xs:pattern>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>

                    <!-- Atributos PERIODICO: TIPO_CLASE-->
                    <xs:attribute name="tipo_clase" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="nacional"/>
                                <xs:enumeration value="internacional"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>


                    <!-- Atributos PERIODICO: FECHA-->
                    <xs:attribute name="fecha_publicacion" type="xs:string"></xs:attribute>

                </xs:complexType>
            </xs:element>

            </xs:sequence>
        </xs:complexType>

    </xs:element>

    
</xs:schema>

=== CAMP09/Lenguajes-XML-DTD-XSD/Actividad2 _Andres/biblioteca_para_XSD.xml
<?xml version="1.0" encoding="UTF-8"?>

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblioteca.xsd">
        <libro id="L0000" tipo_clase="novela" pags="12">
            <titulo></titulo>
            <capitulos>
                <capitulo pags="20">
                    <titulo></titulo>
                    <contenido info="enlace"></contenido>
                </capitulo>
            </capitulos>
            <indice></indice>
            <sinopsis></sinopsis>
        </libro>
  
    <revista id="R0000" tipo_clase="informÃ¡tica" pags="45">
        <titulo></titulo>
        <numero>10</numero>
        <indice></indice>
        <secciones pags="30">
            <contenido info="enlace"></contenido>
        </secciones>
    </revista>

    <periodico id="P0000" tipo_clase="nacional" fecha_publicacion="fecha">
        <indice></indice>
        <seccion tipo_seccion="economica">
            <articulo autor="nombre">
                <contenido info="enlace"></contenido>
            </articulo>
        </seccion>
    </periodico>
</biblioteca>
