=== CAMP09/Lenguajes-XML-DTD-XSD/Actividad 2_Alberto/Validaciones/biblioteca.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
            Esquema que marca la estructura de una biblioteca, con tres elementos libros, revistas y periodicos.
        </xs:documentation>
    </xs:annotation>
<xs:element name="biblioteca">
    <xs:complexType>
        <xs:sequence>
 <!--Elemento libro -->       
            <xs:element name="libros">
                <xs:complexType>
                    <xs:sequence> 
                        <xs:element name="libro">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="titulo_libro" type="xs:string"/>
                                    <!-- varios capítulos con el título en su interior-->
                                    <xs:element name="capitulo" minOccurs="2" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="titulo_capitulo" type="xs:string"/>
                                                <xs:element name="contenido_cap">
                                                    <!--contenido, en el que se tiene un atributo con el enlace a la información -->
                                                    <xs:complexType>
                                                        <xs:attribute name="enlace" type="xs:string" use="required"/>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                            <xs:attribute name="c_paginas" type="xs:string" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="indice_libro" type="xs:string"/>
                                    <xs:element name="sinopsis" type="xs:string"/>
                                </xs:sequence>
                                <!-- Id con restriccion de que empiece por L y luego 4 digitos-->
                                <xs:attribute name="id" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="L\d{4}" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <!-- Restriccion de tipo de libro -->
                                <xs:attribute name="tipo_clase_l" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="novela"/>
                                            <xs:enumeration value="infantil"/>
                                            <xs:enumeration value="didactico"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="paginas" type="xs:integer" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>                                           
            </xs:element>

<!--Elemento revista  --> 
            <xs:element name="revistas">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="revista">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="titulo_revista" minOccurs="1" maxOccurs="1"/>
                                    <xs:element name="numero" minOccurs="1" maxOccurs="unbounded"/>
                                    <xs:element name="indice_revista" minOccurs="1" maxOccurs="unbounded"/>
                                    <xs:element name="seccion_r" minOccurs="1" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="titulo_seccion" type="xs:string"/>
                                                <xs:element name="contenido_rev">
                                                    <!--contenido, en el que se tiene un atributo con el enlace a la información -->
                                                    <xs:complexType>
                                                        <xs:attribute name="enlace" type="xs:string" use="required"/>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                            <xs:attribute name="s_paginas" type="xs:string" use="required"/>
                                        </xs:complexType>
                                    </xs:element>              
                                </xs:sequence> 
                                <xs:attribute name="id" use="required">
                                <!-- Id con restriccion de que empiece por R y luego 4 digitos-->
                                    <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="R\d{4}"/>
                                    </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="tipo_clase_r" use="required">
                                <!-- Restriccion de tipo de revista -->
                                    <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="informatica"/>
                                        <xs:enumeration value="corazon"/>
                                        <xs:enumeration value="coches"/>
                                        <xs:enumeration value="investigacion"/>
                                        <xs:enumeration value="otras"/>
                                    </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="paginas" type="xs:integer" use="required"/> 
                            </xs:complexType>
                        </xs:element> 
                    </xs:sequence>                       
                </xs:complexType>
            </xs:element>

<!--Elemento periodico --> 
            <xs:element name="periodicos">
                <xs:complexType>
                    <xs:sequence>                    
                        <xs:element name="periodico">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="seccion" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                        <xs:element name="articulo" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                            <xs:attribute name="autor" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        </xs:sequence>
                                        <!-- atributo identificativo del tipo de sección, que puede ser: económica, opinión, deportes, nacional o internaciona-->
                                        <xs:attribute name="tipo_seccion" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                            <xs:enumeration value="economica"/>
                                            <xs:enumeration value="opinion"/>
                                            <xs:enumeration value="deportes"/>
                                            <xs:enumeration value="nacional"/>
                                            <xs:enumeration value="internacional"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                        </xs:attribute>
                                    </xs:complexType>
                                    </xs:element>
                                    <xs:element name="indice_periodico" type="xs:string"/>
                                    <!--el contenido será el último elemento del árbol, que necesita un atributo que referencie a la información -->
                                    <xs:element name="contenido">
                                    <xs:complexType>
                                        <xs:attribute name="enlace" type="xs:string" use="required"/>
                                    </xs:complexType>
                                    </xs:element>
                                </xs:sequence> 
                                <xs:attribute name="id" use="required">
                                <!-- Id con restriccion de que empiece por P y luego 4 digitos-->
                                    <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="P\d{4}"/>
                                    </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="tipo_clase_p" use="required">
                                <!-- Restriccion de tipo de periodico -->
                                    <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="nacional"/>
                                        <xs:enumeration value="internacional"/>
                                    </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="fecha_publicacion" type="xs:date" use="required"/> 
                            </xs:complexType>
                        </xs:element>   
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>      
    </xs:complexType>
</xs:element>
</xs:schema>

=== CAMP09/Lenguajes-XML-DTD-XSD/Alberto Actividad 2/biblioteca_XSD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!-- XSD -->
 <!-- Biblioteca   -->
 <biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        	xsi:noNamespaceSchemaLocation= "./Validaciones/biblioteca.xsd"> 

	<libros>
		<libro id="L0001" tipo_clase_l="didáctico" paginas="250">
            <titulo_libro>Validaciones de XML para novatos</titulo_libro>
            <capitulo c_paginas="10" >
                <titulo_capitulo>Introducción XSD</titulo_capitulo>
                <contenido_cap enlace="www.restricciones"/>
            </capitulo>
            <capitulo c_paginas="20">
                <titulo_capitulo>Restricciones XSD</titulo_capitulo>
                <contenido_cap enlace="www.restricciones"/>
            </capitulo>
            <indice_libro>Índice</indice_libro>
            <sinopsis>Este libro es una introducción a XSD para desarrolladores principiantes.</sinopsis>
        </libro>
	</libros>


	<revistas>
		<revista id="R0001" tipo_clase_r="informática" paginas="50">
            <titulo_revista>Revista de informática</titulo_revista>
            <numero >1</numero>
            <indice_revista></indice_revista>
            <seccion_r s_paginas="80">
                <titulo_seccion> Programacion</titulo_seccion>
                <contenido_rev enlace="http://ejemplo.com/articulo3" />
            </seccion_r>
        </revista>
	</revistas>

	<periodicos>
		<periodico id="P1234" tipo_clase_p="nacional" fecha_publicacion="2023-05-05">
            <seccion tipo_seccion="deportes">
                <articulo autor="Alberto Arroyo"></articulo>
            </seccion>
            <indice_periodico>Edix informacion</indice_periodico>
            <contenido enlace="http://ejemplo.com/articulo3" />
        </periodico>
	</periodicos>

</biblioteca>
